#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xA824BB69F2A99A18 (lav@yars.free.net)
#
Name     : lftp
Version  : 4.8.4
Release  : 2
URL      : http://lftp.yar.ru/ftp/lftp-4.8.4.tar.xz
Source0  : http://lftp.yar.ru/ftp/lftp-4.8.4.tar.xz
Source99 : http://lftp.yar.ru/ftp/lftp-4.8.4.tar.xz.asc
Summary  : Sophisticated CLI file transfer program
Group    : Development/Tools
License  : GPL-3.0 LGPL-2.0
Requires: lftp-bin
Requires: lftp-lib
Requires: lftp-data
Requires: lftp-license
Requires: lftp-locales
Requires: lftp-man
BuildRequires : bison
BuildRequires : expat-dev
BuildRequires : glibc-locale
BuildRequires : ncurses-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(zlib)
BuildRequires : readline-dev
BuildRequires : zlib-dev

%description
lftp is CLI file transfer program. It supports FTP, HTTP, FISH and
SFTP protocols, has lots of features including mirror. It was designed
with reliability in mind. GNU Readline library is used for input.
There is also support for secure variants of FTP and HTTP.

%package bin
Summary: bin components for the lftp package.
Group: Binaries
Requires: lftp-data
Requires: lftp-license
Requires: lftp-man

%description bin
bin components for the lftp package.


%package data
Summary: data components for the lftp package.
Group: Data

%description data
data components for the lftp package.


%package dev
Summary: dev components for the lftp package.
Group: Development
Requires: lftp-lib
Requires: lftp-bin
Requires: lftp-data
Provides: lftp-devel

%description dev
dev components for the lftp package.


%package lib
Summary: lib components for the lftp package.
Group: Libraries
Requires: lftp-data
Requires: lftp-license

%description lib
lib components for the lftp package.


%package license
Summary: license components for the lftp package.
Group: Default

%description license
license components for the lftp package.


%package locales
Summary: locales components for the lftp package.
Group: Default

%description locales
locales components for the lftp package.


%package man
Summary: man components for the lftp package.
Group: Default

%description man
man components for the lftp package.


%prep
%setup -q -n lftp-4.8.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534475231
%configure --disable-static --disable-rpath \
--disable-silent-rules \
--enable-largefile \
--with-debug \
--with-expat \
--with-libidn2 \
--with-modules \
--with-openssl \
--with-pager=/usr/bin/less \
--without-gnutls \
--without-included-regex \
--without-profiling
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1534475231
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/lftp
cp COPYING %{buildroot}/usr/share/doc/lftp/COPYING
cp lib/COPYING.LIB %{buildroot}/usr/share/doc/lftp/lib_COPYING.LIB
%make_install
%find_lang lftp

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lftp
/usr/bin/lftpget

%files data
%defattr(-,root,root,-)
/usr/share/applications/lftp.desktop
/usr/share/icons/hicolor/48x48/apps/lftp-icon.png
/usr/share/lftp/convert-mozilla-cookies
/usr/share/lftp/import-ncftp
/usr/share/lftp/import-netscape
/usr/share/lftp/verify-file
/usr/share/lftp/xdg-move

%files dev
%defattr(-,root,root,-)
/usr/lib64/liblftp-jobs.so
/usr/lib64/liblftp-tasks.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/lftp/4.8.4/cmd-mirror.so
/usr/lib64/lftp/4.8.4/cmd-sleep.so
/usr/lib64/lftp/4.8.4/cmd-torrent.so
/usr/lib64/lftp/4.8.4/liblftp-network.so
/usr/lib64/lftp/4.8.4/liblftp-pty.so
/usr/lib64/lftp/4.8.4/proto-file.so
/usr/lib64/lftp/4.8.4/proto-fish.so
/usr/lib64/lftp/4.8.4/proto-ftp.so
/usr/lib64/lftp/4.8.4/proto-http.so
/usr/lib64/lftp/4.8.4/proto-sftp.so
/usr/lib64/liblftp-jobs.so.0
/usr/lib64/liblftp-jobs.so.0.0.0
/usr/lib64/liblftp-tasks.so.0
/usr/lib64/liblftp-tasks.so.0.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/lftp/COPYING
/usr/share/doc/lftp/lib_COPYING.LIB

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/lftp.1
/usr/share/man/man1/lftpget.1
/usr/share/man/man5/lftp.conf.5

%files locales -f lftp.lang
%defattr(-,root,root,-)

