#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xA824BB69F2A99A18 (lav@yars.free.net)
#
Name     : lftp
Version  : 4.9.2
Release  : 9
URL      : http://lftp.yar.ru/ftp/lftp-4.9.2.tar.xz
Source0  : http://lftp.yar.ru/ftp/lftp-4.9.2.tar.xz
Source1  : http://lftp.yar.ru/ftp/lftp-4.9.2.tar.xz.asc
Summary  : Sophisticated CLI file transfer program
Group    : Development/Tools
License  : GPL-3.0 LGPL-2.0
Requires: lftp-bin = %{version}-%{release}
Requires: lftp-data = %{version}-%{release}
Requires: lftp-lib = %{version}-%{release}
Requires: lftp-license = %{version}-%{release}
Requires: lftp-locales = %{version}-%{release}
Requires: lftp-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : expat-dev
BuildRequires : glibc-locale
BuildRequires : ncurses-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(zlib)
BuildRequires : readline-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
lftp is CLI file transfer program. It supports FTP, HTTP, FISH and
SFTP protocols, has lots of features including mirror. It was designed
with reliability in mind. GNU Readline library is used for input.
There is also support for secure variants of FTP and HTTP.

%package bin
Summary: bin components for the lftp package.
Group: Binaries
Requires: lftp-data = %{version}-%{release}
Requires: lftp-license = %{version}-%{release}

%description bin
bin components for the lftp package.


%package data
Summary: data components for the lftp package.
Group: Data

%description data
data components for the lftp package.


%package dev
Summary: dev components for the lftp package.
Group: Development
Requires: lftp-lib = %{version}-%{release}
Requires: lftp-bin = %{version}-%{release}
Requires: lftp-data = %{version}-%{release}
Provides: lftp-devel = %{version}-%{release}
Requires: lftp = %{version}-%{release}

%description dev
dev components for the lftp package.


%package lib
Summary: lib components for the lftp package.
Group: Libraries
Requires: lftp-data = %{version}-%{release}
Requires: lftp-license = %{version}-%{release}

%description lib
lib components for the lftp package.


%package license
Summary: license components for the lftp package.
Group: Default

%description license
license components for the lftp package.


%package locales
Summary: locales components for the lftp package.
Group: Default

%description locales
locales components for the lftp package.


%package man
Summary: man components for the lftp package.
Group: Default

%description man
man components for the lftp package.


%prep
%setup -q -n lftp-4.9.2
cd %{_builddir}/lftp-4.9.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689801661
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static --disable-rpath \
--disable-silent-rules \
--enable-largefile \
--with-debug \
--with-expat \
--with-libidn2 \
--with-modules \
--with-openssl \
--with-pager=/usr/bin/less \
--without-gnutls \
--without-included-regex \
--without-profiling
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1689801661
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lftp
cp %{_builddir}/lftp-%{version}/COPYING %{buildroot}/usr/share/package-licenses/lftp/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/lftp-%{version}/lib/COPYING.LIB %{buildroot}/usr/share/package-licenses/lftp/44f7289042b71631acac29b2f143330d2da2479e || :
%make_install
%find_lang lftp

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lftp
/usr/bin/lftpget

%files data
%defattr(-,root,root,-)
/usr/share/applications/lftp.desktop
/usr/share/icons/hicolor/48x48/apps/lftp-icon.png
/usr/share/lftp/convert-mozilla-cookies
/usr/share/lftp/import-ncftp
/usr/share/lftp/import-netscape
/usr/share/lftp/verify-file
/usr/share/lftp/xdg-move

%files dev
%defattr(-,root,root,-)
/usr/lib64/liblftp-jobs.so
/usr/lib64/liblftp-tasks.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/lftp/4.9.2/cmd-mirror.so
/usr/lib64/lftp/4.9.2/cmd-sleep.so
/usr/lib64/lftp/4.9.2/cmd-torrent.so
/usr/lib64/lftp/4.9.2/liblftp-network.so
/usr/lib64/lftp/4.9.2/liblftp-pty.so
/usr/lib64/lftp/4.9.2/proto-file.so
/usr/lib64/lftp/4.9.2/proto-fish.so
/usr/lib64/lftp/4.9.2/proto-ftp.so
/usr/lib64/lftp/4.9.2/proto-http.so
/usr/lib64/lftp/4.9.2/proto-sftp.so
/usr/lib64/liblftp-jobs.so.0
/usr/lib64/liblftp-jobs.so.0.0.0
/usr/lib64/liblftp-tasks.so.0
/usr/lib64/liblftp-tasks.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lftp/44f7289042b71631acac29b2f143330d2da2479e
/usr/share/package-licenses/lftp/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lftp.1
/usr/share/man/man1/lftpget.1
/usr/share/man/man5/lftp.conf.5

%files locales -f lftp.lang
%defattr(-,root,root,-)

